apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-gxl8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/dev-release-team-tenant/appstudio/dc-metro-map-gxl8@sha256:40c67ca6caa2fea8f3b39a36e0ad2d14b2dc7d202f7356286c6d84b0cf5aa3ae
        name: my-nodejs
        resources: {}
status: {}
